# Generated by Django 6.0.2 on 2026-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_profile_roles_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
