# Generated by Django 6.0.2 on 2026-03-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_profile_display_username_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
