# Generated by Django 6.0.2 on 2026-03-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_profile_display_username'),
        ('MyApp', '0004_profile_address_line1_profile_address_line2_and_more'),
    ]

    operations = [
    ]
