# Generated by Django 6.0.2 on 2026-03-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('blankets', 'Blankets / Bedding'), ('hygiene', 'Hygiene Items'), ('transport', 'Transportation'), ('medical', 'Medical Supplies')], max_length=20)),
                ('city', models.CharField(max_length=60)),
                ('location_details', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_claimed', to='MyApp.profile')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='MyApp.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
