# Generated by Django 5.2.11 on 2026-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_favoritelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
